### PR TITLE
move projects from  '.\RhetosPackages\Source' to '.\Plugins\'

### PR DESCRIPTION
**Pull request by thanhlm91**

### CODE REVIEW

**Comment by thanhlm91** [comment]
this pr will resove issue #24

**Review by nguyenlamlll — CHANGES_REQUESTED** [review]
Let us merge branch `update_rhetos_build` into this branch first. Then remove the projects inside `.\RhetosPackages\Source` directory.

**Comment by huynguyen-95** [comment]
Can't delete it right now because it will conflict with my PR #25

**Comment by nguyenlamlll** [comment]
@thanhlm91 Hi, looks like #25 is merged. Can you please update this PR with latest `master` and move new files to the new directory again? Thanks!

**Comment by nguyenlamlll** [comment]
Close this as we moved to #29.

**Pull request closed without merging**
