### PR TITLE
Changes double quotes to single quotes in Typescript templates

### LINKED ISSUE #34: TypeScriptException when a validation message contains quotes
DeployPackages fails with TypeScriptException on deployment if the application contains the following DSL script:

```
Module TestAdminGuid
{
    Entity TestE
    {
        ShortString Name;

        ItemFilter StartsWithX 'item => item.Name.StartsWith("X")';
        InvalidData StartsWithX 'Name should not start with "X".';
    }
}
```

DeployPackages log:

```
[Trace] DeployPackages: > adminGui@1.0.0 tsc C:\My Projects\Rhetos\Source\Rhetos\Resources\AdminGuiCompile
[Trace] DeployPackages: > tsc
[Trace] DeployPackages:
[Trace] DeployPackages: scripts/models/rhetos.angular2.ts(951,112): error TS1005: ',' expected.
[Trace] DeployPackages: scripts/models/rhetos.angular2.ts(951,113): error TS1005: ':' expected.
...
[Error] DeployPackages: Angular2ModelGenerator.Exceptions.TypeScriptException: Compiling TypeScript models failed.
```

Here is the part of the *rhetos.angular2.ts* that causes the error (line 951):

```typescript
949    getInvalidDataDefinitions():Array<IInvalidDataFilter> {
950        return [
951            { name:" StartsWithX ", filter: "TestAdminGuid.StartsWithX", message: "Name should not start with "X"." }
952        ];
953    }
```

### PR DESCRIPTION
**Pull request by huynguyen-95**
In **Rhetos.Angular2.ts**, string often in double quotes, so I change it to single quotes for using double quotes inside string.

This will resolve issue fixes #34 and #33

### CODE REVIEW

**Review by bantolov — CHANGES_REQUESTED** [review]
I like this change to single quotes because we don't need to write two quotes ("") for a each quote in C# strings.

But now the deployment fails on messages that contain **single quotes** (for example one core plugin has an InvalidData validation with a message that contains "remove the domain prefix from the role's name to stop AD synchronization."
When generating typescript code for error messages, we should [escape](https://stackoverflow.com/questions/39912555/angular-2-expression-single-quote-escape) the single quotes in the generated strings that might contain them. This is probably required only for `{regex}` and `{errorMessage}`. Identifiers such as entity name or module name cannot contain quotes.

**Comment by nguyenquanghuy031295** [comment]
Thanks for your examples @bantolov. Do you have some example about regex contains single quote?

**Comment by huynguyen-95** [comment]
Solved, you could check again @bantolov.

**Comment by bantolov** [comment]
It works on both cases on my tests.

**Review by bantolov — APPROVED** [review]

**Pull request merged**
